/**
 * @fileoverview gRPC-Web generated client stub for greet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.16.3
// source: chats.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as chats_pb from './chats_pb';


export class ChatRoomClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSend = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/Send',
    grpcWeb.MethodType.UNARY,
    chats_pb.ChatMessage,
    chats_pb.ChatRequest,
    (request: chats_pb.ChatMessage) => {
      return request.serializeBinary();
    },
    chats_pb.ChatRequest.deserializeBinary
  );

  send(
    request: chats_pb.ChatMessage,
    metadata: grpcWeb.Metadata | null): Promise<chats_pb.ChatRequest>;

  send(
    request: chats_pb.ChatMessage,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chats_pb.ChatRequest) => void): grpcWeb.ClientReadableStream<chats_pb.ChatRequest>;

  send(
    request: chats_pb.ChatMessage,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chats_pb.ChatRequest) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.ChatRoom/Send',
        request,
        metadata || {},
        this.methodDescriptorSend,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.ChatRoom/Send',
    request,
    metadata || {},
    this.methodDescriptorSend);
  }

  methodDescriptorJoinChat = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/JoinChat',
    grpcWeb.MethodType.SERVER_STREAMING,
    chats_pb.ChatRequest,
    chats_pb.MessageDto,
    (request: chats_pb.ChatRequest) => {
      return request.serializeBinary();
    },
    chats_pb.MessageDto.deserializeBinary
  );

  joinChat(
    request: chats_pb.ChatRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<chats_pb.MessageDto> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/greet.ChatRoom/JoinChat',
      request,
      metadata || {},
      this.methodDescriptorJoinChat);
  }

  methodDescriptorCreateChat = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/CreateChat',
    grpcWeb.MethodType.UNARY,
    chats_pb.CreateChatRequestDto,
    chats_pb.CreateChatResponseDto,
    (request: chats_pb.CreateChatRequestDto) => {
      return request.serializeBinary();
    },
    chats_pb.CreateChatResponseDto.deserializeBinary
  );

  createChat(
    request: chats_pb.CreateChatRequestDto,
    metadata: grpcWeb.Metadata | null): Promise<chats_pb.CreateChatResponseDto>;

  createChat(
    request: chats_pb.CreateChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chats_pb.CreateChatResponseDto) => void): grpcWeb.ClientReadableStream<chats_pb.CreateChatResponseDto>;

  createChat(
    request: chats_pb.CreateChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chats_pb.CreateChatResponseDto) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.ChatRoom/CreateChat',
        request,
        metadata || {},
        this.methodDescriptorCreateChat,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.ChatRoom/CreateChat',
    request,
    metadata || {},
    this.methodDescriptorCreateChat);
  }

  methodDescriptorAddUserToChat = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/AddUserToChat',
    grpcWeb.MethodType.UNARY,
    chats_pb.AddUserToChatRequestDto,
    chats_pb.AddUserToChatResponseDto,
    (request: chats_pb.AddUserToChatRequestDto) => {
      return request.serializeBinary();
    },
    chats_pb.AddUserToChatResponseDto.deserializeBinary
  );

  addUserToChat(
    request: chats_pb.AddUserToChatRequestDto,
    metadata: grpcWeb.Metadata | null): Promise<chats_pb.AddUserToChatResponseDto>;

  addUserToChat(
    request: chats_pb.AddUserToChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chats_pb.AddUserToChatResponseDto) => void): grpcWeb.ClientReadableStream<chats_pb.AddUserToChatResponseDto>;

  addUserToChat(
    request: chats_pb.AddUserToChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chats_pb.AddUserToChatResponseDto) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.ChatRoom/AddUserToChat',
        request,
        metadata || {},
        this.methodDescriptorAddUserToChat,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.ChatRoom/AddUserToChat',
    request,
    metadata || {},
    this.methodDescriptorAddUserToChat);
  }

  methodDescriptorGetChats = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/GetChats',
    grpcWeb.MethodType.UNARY,
    chats_pb.GetChatsRequestDto,
    chats_pb.GetChatsResponseDto,
    (request: chats_pb.GetChatsRequestDto) => {
      return request.serializeBinary();
    },
    chats_pb.GetChatsResponseDto.deserializeBinary
  );

  getChats(
    request: chats_pb.GetChatsRequestDto,
    metadata: grpcWeb.Metadata | null): Promise<chats_pb.GetChatsResponseDto>;

  getChats(
    request: chats_pb.GetChatsRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: chats_pb.GetChatsResponseDto) => void): grpcWeb.ClientReadableStream<chats_pb.GetChatsResponseDto>;

  getChats(
    request: chats_pb.GetChatsRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: chats_pb.GetChatsResponseDto) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.ChatRoom/GetChats',
        request,
        metadata || {},
        this.methodDescriptorGetChats,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.ChatRoom/GetChats',
    request,
    metadata || {},
    this.methodDescriptorGetChats);
  }

}

