/**
 * @fileoverview gRPC-Web generated client stub for greet
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.1
// 	protoc              v3.16.3
// source: greet.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as greet_pb from './greet_pb';


export class ChatRoomClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateChat = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/CreateChat',
    grpcWeb.MethodType.UNARY,
    greet_pb.CreateChatRequestDto,
    greet_pb.CreateChatResponseDto,
    (request: greet_pb.CreateChatRequestDto) => {
      return request.serializeBinary();
    },
    greet_pb.CreateChatResponseDto.deserializeBinary
  );

  createChat(
    request: greet_pb.CreateChatRequestDto,
    metadata: grpcWeb.Metadata | null): Promise<greet_pb.CreateChatResponseDto>;

  createChat(
    request: greet_pb.CreateChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greet_pb.CreateChatResponseDto) => void): grpcWeb.ClientReadableStream<greet_pb.CreateChatResponseDto>;

  createChat(
    request: greet_pb.CreateChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greet_pb.CreateChatResponseDto) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.ChatRoom/CreateChat',
        request,
        metadata || {},
        this.methodDescriptorCreateChat,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.ChatRoom/CreateChat',
    request,
    metadata || {},
    this.methodDescriptorCreateChat);
  }

  methodDescriptorAddUserToChat = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/AddUserToChat',
    grpcWeb.MethodType.UNARY,
    greet_pb.AddUserToChatRequestDto,
    greet_pb.AddUserToChatResponseDto,
    (request: greet_pb.AddUserToChatRequestDto) => {
      return request.serializeBinary();
    },
    greet_pb.AddUserToChatResponseDto.deserializeBinary
  );

  addUserToChat(
    request: greet_pb.AddUserToChatRequestDto,
    metadata: grpcWeb.Metadata | null): Promise<greet_pb.AddUserToChatResponseDto>;

  addUserToChat(
    request: greet_pb.AddUserToChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greet_pb.AddUserToChatResponseDto) => void): grpcWeb.ClientReadableStream<greet_pb.AddUserToChatResponseDto>;

  addUserToChat(
    request: greet_pb.AddUserToChatRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greet_pb.AddUserToChatResponseDto) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.ChatRoom/AddUserToChat',
        request,
        metadata || {},
        this.methodDescriptorAddUserToChat,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.ChatRoom/AddUserToChat',
    request,
    metadata || {},
    this.methodDescriptorAddUserToChat);
  }

  methodDescriptorGetChats = new grpcWeb.MethodDescriptor(
    '/greet.ChatRoom/GetChats',
    grpcWeb.MethodType.UNARY,
    greet_pb.GetChatsRequestDto,
    greet_pb.GetChatsResponseDto,
    (request: greet_pb.GetChatsRequestDto) => {
      return request.serializeBinary();
    },
    greet_pb.GetChatsResponseDto.deserializeBinary
  );

  getChats(
    request: greet_pb.GetChatsRequestDto,
    metadata: grpcWeb.Metadata | null): Promise<greet_pb.GetChatsResponseDto>;

  getChats(
    request: greet_pb.GetChatsRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greet_pb.GetChatsResponseDto) => void): grpcWeb.ClientReadableStream<greet_pb.GetChatsResponseDto>;

  getChats(
    request: greet_pb.GetChatsRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greet_pb.GetChatsResponseDto) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.ChatRoom/GetChats',
        request,
        metadata || {},
        this.methodDescriptorGetChats,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.ChatRoom/GetChats',
    request,
    metadata || {},
    this.methodDescriptorGetChats);
  }

}

export class AuthClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorLogin = new grpcWeb.MethodDescriptor(
    '/greet.Auth/Login',
    grpcWeb.MethodType.UNARY,
    greet_pb.LoginRequestDto,
    greet_pb.LoginResponseDto,
    (request: greet_pb.LoginRequestDto) => {
      return request.serializeBinary();
    },
    greet_pb.LoginResponseDto.deserializeBinary
  );

  login(
    request: greet_pb.LoginRequestDto,
    metadata: grpcWeb.Metadata | null): Promise<greet_pb.LoginResponseDto>;

  login(
    request: greet_pb.LoginRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greet_pb.LoginResponseDto) => void): grpcWeb.ClientReadableStream<greet_pb.LoginResponseDto>;

  login(
    request: greet_pb.LoginRequestDto,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greet_pb.LoginResponseDto) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.Auth/Login',
        request,
        metadata || {},
        this.methodDescriptorLogin,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.Auth/Login',
    request,
    metadata || {},
    this.methodDescriptorLogin);
  }

  methodDescriptorCheck = new grpcWeb.MethodDescriptor(
    '/greet.Auth/Check',
    grpcWeb.MethodType.UNARY,
    greet_pb.Void,
    greet_pb.Void,
    (request: greet_pb.Void) => {
      return request.serializeBinary();
    },
    greet_pb.Void.deserializeBinary
  );

  check(
    request: greet_pb.Void,
    metadata: grpcWeb.Metadata | null): Promise<greet_pb.Void>;

  check(
    request: greet_pb.Void,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: greet_pb.Void) => void): grpcWeb.ClientReadableStream<greet_pb.Void>;

  check(
    request: greet_pb.Void,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: greet_pb.Void) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/greet.Auth/Check',
        request,
        metadata || {},
        this.methodDescriptorCheck,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/greet.Auth/Check',
    request,
    metadata || {},
    this.methodDescriptorCheck);
  }

}

